spring.application.name=SpringEcom

spring.datasource.url=jdbc:postgresql://localhost:5432/fr3nzy

spring.datasource.username=postgres
spring.datasource.password=1039

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.datasource.hikari.ddl-auto=update

